mybatis:
  configuration:
    map-underscore-to-camel-case: true
  database:
    type: mysql
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml,classpath*:mapper/*.xml
  mapperLocations: classpath*:mapper/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  model:
    pack: com.huang.springbootdemo.entity
  table:
    auto: update
  type-aliases-package: com.huang.springbootdemo.entity
server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456aA@
    url: jdbc:mysql://120.79.218.158:3306/test?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root


